### ISSUE TITLE
GAP install error

### ISSUE THREAD

**Issue by nvica** [xnl-h4ck3r/GAP-Burp-Extension#12]
Hello during the installation of GAP I receive the error. Any idea how I can do?

>  java -jar jython-standalone-2.7.3.jar -m pip install -r requirements.txt
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
DEPRECATION: A future version of pip will drop support for Python 2.7.
ERROR: Invalid requirement: "<!DOCTYPE html>"

**Comment by xnl-h4ck3r** [comment]
Hi @nvica . Are you running that command in the folder where the JAR file is, and have you got the `requirements,txt` file from the repo in that folder too?

**Comment by nvica** [comment]
yes 
![Capture d’écran du 2023-03-03 14-53-18](https://user-images.githubusercontent.com/62671571/222739489-5c5eee21-9752-46e3-9894-4d5d4e509a6f.png)

**Comment by xnl-h4ck3r** [comment]
Hi. Can you check that requirements.txt in that folder is the one from the repo? It should just have the 3 library names and nothing else in it. I'm not sure why it's saying that line is in it

**Comment by nvica** [comment]
Sorry, it was a mistake on my part. Thank you for your help.

**Comment by xnl-h4ck3r** [comment]
No problem! Thanks for using GAP!
