### ISSUE TITLE
error

### ISSUE THREAD

**Issue by jinzezhi** [xnl-h4ck3r/GAP-Burp-Extension#14]
Symptom An error occurs when the java -jar jython-stand 2.7.3.jar -m pip install -r requirements.txt command is executed on windows
![image](https://user-images.githubusercontent.com/93123422/228462722-482259c1-d949-43e8-9d9a-4e40972e0b44.png)

**Comment by xnl-h4ck3r** [comment]
> Hi @jinzezhi, can you try updating pip with python -m pip install -U pip and try again?

Hi @jinzezhi, did you get a chance to try this? Did it make any difference?
