### ISSUE TITLE
Request to add timestamp to autosaved files

### ISSUE THREAD

**Issue by 0xm4v3rick** [xnl-h4ck3r/GAP-Burp-Extension#16]
Hi @xnl-h4ck3r 

Thanks for making this extension and more importantly keep it actively maintained. Wanted to see if it would be good to have files saved automatically with a timestamp in the file name to avoid overwriting the previous once.
It helps for a person like me who can use this extension on same over periods of time while testing various different sections of the domains. I have a hacky version of this for my own use. I can make a PR if it sounds good.

Thanks!

**Comment by xnl-h4ck3r** [comment]
Hey @0xm4v3rick 
Thanks for using GAP. I'm not sure if you're using an old version, but the files that are saved do have a time stamp now, and they are organised in folders by root, and also include a complete file per mode with all roots if you selected multiple

**Comment by xnl-h4ck3r** [comment]
No problem! Thanks again for using it
