### ISSUE TITLE
bs4 warring

### ISSUE THREAD

**Issue by ali-0x11** [xnl-h4ck3r/GAP-Burp-Extension#17]
after installing the extension I got this warning 
![Screenshot 2023-05-11 122223](https://github.com/xnl-h4ck3r/GAP-Burp-Extension/assets/29012780/238a2652-969e-4a67-bcce-4ae9ad9bccbd)

**Comment by xnl-h4ck3r** [comment]
Hi @KalingGo 
Did you follow all of the Installation Instructions on the README? Did you get any errors when running these?
Regards
Xnl

**Comment by xnl-h4ck3r** [comment]
I'm going to close this now. The errors shown are what happens if you don't follow the Installation instructions. It will work like this, but Word mode won't be available
