### ISSUE TITLE
WARNING: Could not import beauttifulsoup4 for word mode: No module named bs4

### ISSUE THREAD

**Issue by da7om85** [xnl-h4ck3r/GAP-Burp-Extension#18]
WARNING: Could not import beauttifulsoup4 for word mode: No module named bs4

**Comment by da7om85** [comment]
![image](https://github.com/xnl-h4ck3r/GAP-Burp-Extension/assets/15123518/253de6e2-46f5-4c66-ad35-ed3446bbf601)

**Comment by xnl-h4ck3r** [comment]
Hi @da7om85. It looks like you didn't follow the instructions here https://github.com/xnl-h4ck3r/GAP-Burp-Extension#installation
You need to install the requirements using the latest Jython jar file to make it available inside Burp.
Thanks
Xnl

**Comment by xnl-h4ck3r** [comment]
Hi @da7om85, did you have any luck after following the instructions?

**Comment by da7om85** [comment]
Hello @xnl-h4ck3r 

same issue

![image](https://github.com/xnl-h4ck3r/GAP-Burp-Extension/assets/15123518/667106b3-b0d3-4232-89b4-b6bf58a2c370)

![image](https://github.com/xnl-h4ck3r/GAP-Burp-Extension/assets/15123518/6dcca3ca-2e82-4b41-83a4-266af23d8181)

However, the extension works without any issues; I'm just wondering why I got this error.

```
WARNING: Could not import beauttifulsoup4 for word mode: No module named bs4
GAP - Version 3.5
by @xnl_h4ck3r

The full Help documentation can be found at https://github.com/xnl-h4ck3r/GAP-Burp-Extension/blob/main/GAP%20Help.md or from the Help icon on the GAP tab

If you ever see anything in the Errors tab, please raise an issue on Github so I can fix it!
Want to buy me a coffee?! - https://ko-fi.com/B0B3CZKR5

WARNING: Could not import html5lib for more accurate parsing of words by beatifulsoup4 library.
```

**Comment by xnl-h4ck3r** [comment]
Hi @da7om85. Did you  follow the instructions on the README? This error happens when you don't install with those instructions

**Comment by da7om85** [comment]
Hello @xnl-h4ck3r 

After following all instructions, the issue fixed.

Thank you,

![image](https://github.com/xnl-h4ck3r/GAP-Burp-Extension/assets/15123518/20002ae5-78f6-4f21-bfb1-27bc6c1cf148)

**Comment by xnl-h4ck3r** [comment]
Great! I hope you find the tool useful. Thanks for using GAP 🤘
