### ISSUE TITLE
GAP doesn't collect words properly with "-"

### ISSUE THREAD

**Issue by bebiksior** [xnl-h4ck3r/GAP-Burp-Extension#20]
Hello :-)

I've noticed that GAP doesn't collect words properly from URL paths that look like this:
`/api/custom-polls/home/pending-draft-polls-count` 

Right now it collects only the following words:
`api,custom,pools,home,pending,draft,polls,count`

I think it should collect the following words:
`api,custom-pools,custom,pools,home,pending-draft-polls-count,pending,draft,count`

For some reason, it ignores words with "-". Is this intentional?

**Comment by xnl-h4ck3r** [comment]
Hi @bebiksior, thanks for raising the issue!
