### ISSUE TITLE
Can't access Other options when display font-size are set to 16

### ISSUE THREAD

**Issue by SONGOKU100** [xnl-h4ck3r/GAP-Burp-Extension#23]
![image](https://github.com/xnl-h4ck3r/GAP-Burp-Extension/assets/64953625/8d8592e4-141d-4c15-b51b-586d83574d50)
when font-size is set to 15, 16 then other options can't be accessed. Can UI be made scrollable so the font-size doesn't affect it?

**Comment by xnl-h4ck3r** [comment]
Hi @SONGOKU100 , sorry for this issue. Trying to get it all to display on different size monitors, with different sized fonts, etc. is so hard to get right, especially with the horrible UI that you need to use for Burp :/

I'm afraid I'm going to struggle doing more to get it better at the moment. 
I know it's not a great solution, but in the newest version of Burp, you can hide tabs you don't use (or detach them) and so if they didn't wrap to 2 lines, the display should be ok. The only other way for now is to unfortunately use font-size of 14.

Another option you have now until I can think of a better way is to remove the logo banner at the top. There are 2 occurrences of the following code in GAP.py:
```
      .addComponent(self.btnLogo,
                                GroupLayout.PREFERRED_SIZE,
                                GroupLayout.PREFERRED_SIZE,
                                GroupLayout.PREFERRED_SIZE,
                                )
```
If you remove both of these, you may be able to see the rest of the controls.

Apologies it's not a great fix for now.
Regards
Xnl

**Comment by xnl-h4ck3r** [comment]
Hi @SONGOKU100 
I know it's not a proper solution to this problem, but if you get v4.0 you can click the GAP logo banner while holding CTRL and it will remove it. This might help in the meantime
