### ISSUE TITLE
GAP not showing in Burpsuite

### ISSUE THREAD

**Issue by evalihub** [xnl-h4ck3r/GAP-Burp-Extension#24]
I have tried:

- updating burp
- reinstalling my python env
- updating latest version of GAP
- restarting burp / restarting PC

Extension says its installed but is not showing up in burp, other python extensions are working.

Not getting any error messages when installing:

![image](https://github.com/xnl-h4ck3r/GAP-Burp-Extension/assets/117573633/99760391-8f6f-46f5-9e41-a54b0f8f71fc)

![image](https://github.com/xnl-h4ck3r/GAP-Burp-Extension/assets/117573633/686963ca-93ff-4391-9dbb-77c071ed7144)

Here we can see when the extension, but there is no tab in Burp to view the results

<img width="334" alt="image" src="https://github.com/xnl-h4ck3r/GAP-Burp-Extension/assets/117573633/e8ac893b-dbd9-449b-873a-d9457df00125">

<img width="853" alt="image" src="https://github.com/xnl-h4ck3r/GAP-Burp-Extension/assets/117573633/4aba31d0-f06c-4472-b810-8ae3570a8634">

**Comment by evalihub** [comment]
Was resolved using a new Jython standalone

**Comment by xnl-h4ck3r** [comment]
I'm glad you sorted the problem. Thanks for using GAP, I hope you find it useful

**Comment by evalihub** [comment]
It's my most used burp extension. Amazing tool!
