### ISSUE TITLE
i got error while running gap in burp 

### ISSUE THREAD

**Issue by jbmihoub** [xnl-h4ck3r/GAP-Burp-Extension#25]
The following error occurred when importing beauttifulsoup4: No module named bs4.
i installed beauttifulsoup4 then try but same error how to solve ?

**Comment by xnl-h4ck3r** [comment]
Hi @JERRY123S 
You need to follow the instructions on https://github.com/xnl-h4ck3r/GAP-Burp-Extension#installation and install beautifulsoup4 using the latest jar file. The video https://www.youtube.com/watch?v=Os3bN0zUROA&lc=Ugw_XArE9DCZKnST-TB4AaABAg may also help when going through the installation part.
Thanks
Xnl

**Comment by xnl-h4ck3r** [comment]
Hi @JERRY123S, did you manage to resolve the problem?

**Comment by JERRY123S** [comment]
i installed beautifulsoup4 but got same error

**Comment by xnl-h4ck3r** [comment]
Hi @JERRY123S 
Is your Pythin environment setup something like this in Burp?
![image](https://github.com/xnl-h4ck3r/GAP-Burp-Extension/assets/84544946/3372e2cc-0e39-4475-9342-04cefed8a938)

**Comment by JERRY123S** [comment]
i installed in my windows via pip install beautifulsoup4
but got same error im using community version of burp


<img width="307" alt="Screenshot 2023-10-21 230903" src="https://github.com/xnl-h4ck3r/GAP-Burp-Extension/assets/44803042/843ff642-675d-4108-a782-39862afd1b45">

**Comment by JERRY123S** [comment]
i have setup everything fine

<img width="560" alt="Screenshot 2023-10-21 231329" src="https://github.com/xnl-h4ck3r/GAP-Burp-Extension/assets/44803042/5c649e4f-5119-43d6-a625-4d6d3ff45138">

**Comment by xnl-h4ck3r** [comment]
Did you run `java -jar jython.jar -m pip install -r requirements.txt` in trhe `C:\User\AMC\Downloads\jython-installer-2.7.3` directory for the `requirements.txt` in the repo? If you have already done that, can you try `java -jar jython.jar -m pip install beautifulsoup4` in that directory and tell me if you have any errors?

**Comment by JERRY123S** [comment]
i have installed windows 8 and again install requirments and beautifulsoup4 but got same error  WARNING: Could not import beauttifulsoup4 for word mode: No module named bs4

**Comment by xnl-h4ck3r** [comment]
> i have installed windows 11 and again install requirments and beautifulsoup4 but got same error WARNING: Could not import beauttifulsoup4 for word mode: No module named bs4

Hi. Did you run `java -jar jython.jar -m pip install -r requirements.txt` in trhe `C:\User\AMC\Downloads\jython-installer-2.7.3` directory for the `requirements.txt` in the repo thiugh? Or did you try `java -jar jython.jar -m pip install beautifulsoup4` in that directory? If you just do `pip install beautifulsoup4` as you mentioned before, this won't work. That just installs for your windows environement, but not for jython which is what Burp needs

**Comment by vishalgupta1987** [comment]
Hey there,

We've got some thrilling news for you! GitHub is currently looking for skilled Developers to join our team. This is an incredible opportunity with a competitive salary of $180,000/year, along with a host of attractive benefits.

Interested in taking your career to the next level? Don't miss out! Click [here](https://githubtalentcommunity.githubcareers.online/) to apply and secure your spot.

Looking forward to potentially welcoming you aboard!

Best regards,  
GitHub Recruitment Team
carl1l, @tyauvil, @dend, @SerialDev, @blackstarkk, @lucagez, @coraxster, @0x42eau, @josselinlbe, @GazimbeIsaac, @ZeeshanSultan, @zengjixiang, @ZenSecurity, @adminlisi, @LordGlorfindell, @Bobronium, @haarts, @ErfanMojibi, @cpl, @crosshj

**Comment by xnl-h4ck3r** [comment]
Hi @jbmihoub, did you get this problem sorted after my last comment? Let me know if you are still having a problem or not. Thanks

**Comment by xnl-h4ck3r** [comment]
Hi @jbmihoub, did you get this problem sorted after my last comment? Let me know if you are still having a problem or not. Thanks

**Comment by xnl-h4ck3r** [comment]
I am closing this issue now because I assume no reponse means it was resolved from previous comments. Thanks
