### ISSUE TITLE
Parsing Entire Domain no longer works

### ISSUE THREAD

**Issue by zwink2** [xnl-h4ck3r/GAP-Burp-Extension#28]
If a specific .JS file is sent to the GAP extension, it is parsed fine, but if an entire domain (EG: www.something.com) from the target pane is sent to GAP, now it always finds no files to parse.  Using latest version of GAP on latest version of Burp.  Any ideas?

**Comment by xnl-h4ck3r** [comment]
Hi @zwink2 . Have you got scope set? If you call from the Site Map, scope needs to be set for it to work properly there. Sorry if that wasn't clear

**Comment by zwink2** [comment]
Well that does make sense! Thanks for the reply!
