### ISSUE TITLE
AttributeError("'NoneType' object has no attribute 'toString'",)

### ISSUE THREAD

**Issue by mattzamat** [xnl-h4ck3r/GAP-Burp-Extension#3]
Hey there,

I love your tool! It has certainly helped me out countless times with my bounty hunting, so thank you!

I recently noticed this error starting to occur, and only on some burp files...see attachment.

![Screenshot 2022-11-25 at 5 10 28 PM](https://user-images.githubusercontent.com/96935285/204059535-d7eef52d-c9da-457b-bca0-3f29d64cfc03.png)

Let me know your thoughts!

**Comment by xnl-h4ck3r** [comment]
Hey @mattzamat 
Thank you! I'm glad you've found it useful :)
I haven't some across that issue before. Are you able to let me know what target you ran GAP against to cause that error so I can try and rerpoduce it?
Many thanks
Xnl

**Comment by mattzamat** [comment]
Well that was fast! Nice to hear from you, you're awesome for this tool!

Sure, try hitting dashboard.branch.io and seeing if you can reproduce it

**Comment by xnl-h4ck3r** [comment]
Can you just double check you have the latest version?
I've signed up on that site and cllicked around and used a number of features, but not getting that error when I use GAP yet. 
Are you able to send me your Burp project file maybe (not on here, but maybe connect on Discord to arrange that: xnl-h4ck3r#1197)? That would probably help me find the issue a lot quicker. I understand if you don't want to. I'll take a proper look tomorrow.
Many thanks
Xnl

**Comment by mattzamat** [comment]
Sorry, I must have missed this yesterday. As embarrassing as this is, the issue seems to have completely resolved after moving the cloned folder to a different directory? Not quite sure how that worked, but im not having that issue anymore. will definitely reach out if it happens again

On behalf of all the GAP users, thank you!!!!! Really a great tool. You're awesome!

**Comment by xnl-h4ck3r** [comment]
That is weird! I'm glad it's sorted now anyway. While looking into this I found some other bugs anyway, so thanks for taking the time to raise an issue, and thanks for the great feedback! :)

**Comment by mattzamat** [comment]
Awesome. I'll keep an eye out for the updated release! 

Has anyone ever suggested being able to modify the window size in the GAP tab? I find that sometimes I'm more interested in the URL's, more so than the parameters, but I see that the tab height is locked. Maybe I'm missing something, but that would be cool!

**Comment by xnl-h4ck3r** [comment]
There is a new version available now. Burp itself actually throws errors if a URL has a dollar symbol in it and you call the callback inscope method, so I hve avoided passing those if tyhey occur. 
If you do see any further errors then please let me know though. I'm still not sure what caused your initial error though.

You can't adjust the window size at the moment sorry. I'll take a look into it at some point.
Thanks for the suggestions!
Regards
Xnl

**Comment by xnl-h4ck3r** [comment]
> Awesome. I'll keep an eye out for the updated release!
> 
> Has anyone ever suggested being able to modify the window size in the GAP tab? I find that sometimes I'm more interested in the URL's, more so than the parameters, but I see that the tab height is locked. Maybe I'm missing something, but that would be cool!

Hey @mattzamat 
You mentioned wanting to be able to modify the window size in the GAP tab. I've looked into that, but unfortunately the UI of Burp interfaces is a nightmare and uses JSwing which is horrible and I can't get a split window to work properly :(
However, I could easily make it so if you change the GAP Mode to just Parameters it will only show the parameter text box full heioght, and if only the Links was selected, only the Links text box and filters shown full height. Would that be helpful instead?
Regards
Xnl

**Comment by mattzamat** [comment]
That would be more than helpful! Wow, you're fast!

**Comment by xnl-h4ck3r** [comment]
I've just put v1.8 live, so goive it a try and let me know if you have any problems :)
