### ISSUE TITLE
Make the parameters in the "Potential params found" tab with "Show sus" option selected easier to copy

### ISSUE THREAD

**Issue by philipsinnott** [xnl-h4ck3r/GAP-Burp-Extension#30]
Hey :) fantastic job on this extension, however I have a suggestion that would make using it slightly smoother in certain scenarios.

Currently, if you have the "Show sus" option selected, the "Potential params found" tab looks like this:

![bild](https://github.com/xnl-h4ck3r/GAP-Burp-Extension/assets/56341190/d6359075-aef6-440e-abe3-1f5c0272449b)

However, it's not easy to copy & paste because of the **[\<VULNERABILITY-CLASS\>]** text after the parameters. It would be nice if there was an option to either 1) copy the "raw" parameters or 2) toggle the **[\<VULNERABILITY-CLASS\>]** text on/off to easily copy the parameters yourself

Thanks!

**Comment by xnl-h4ck3r** [comment]
Hi @philipsinnott. Thanks for using GAP and taking the time to raise a suggestion. That sounds like a good idea. I'll add it to the TODO list. NOt sure exactly when I'll get to that though

**Comment by xnl-h4ck3r** [comment]
Hi @philipsinnott. In the latest version, v4.9, you can now right click and select `Copy` to copy all entries from the parameters, words and links panes. With the Parameters pane, if Sus Params is selected, and you press `Copy`, it will just copy the parameter names to the clipbaord, not the Vuln types. I gope that fixes your issue
