### ISSUE TITLE
The following error occurred when importing beauttifulsoup4: 'tuple' object has no attribute 'major'

### ISSUE THREAD

**Issue by kN6jq** [xnl-h4ck3r/GAP-Burp-Extension#34]
![image](https://github.com/xnl-h4ck3r/GAP-Burp-Extension/assets/27048404/e751ccc4-7c5a-49ec-b24c-9c4670c99c2c)
![image](https://github.com/xnl-h4ck3r/GAP-Burp-Extension/assets/27048404/a067ffe5-fe97-413b-8321-10c5d9467ff5)
![image](https://github.com/xnl-h4ck3r/GAP-Burp-Extension/assets/27048404/2675b889-e1c4-43a5-aecc-6632b3a850d4)

What can i do to solve the problem

**Comment by xnl-h4ck3r** [comment]
Hi @kN6jq 
Did ypu follow these installation instructoons exactly?
https://github.com/xnl-h4ck3r/GAP-Burp-Extension/blob/main/GAP%20Help.md#how-to-install

**Comment by xnl-h4ck3r** [comment]
Hi @kN6jq. Let me know if you solved the issue after following the instructions exactly, or if there is another issue here. Many thanks

**Comment by matthew2090218687** [comment]
![image](https://github.com/xnl-h4ck3r/GAP-Burp-Extension/assets/62337511/9b4d9f8a-f112-47c1-95f7-8b59ff5b2c41)
![image](https://github.com/xnl-h4ck3r/GAP-Burp-Extension/assets/62337511/bd1a01b6-2fc8-47ba-81f7-4ebe45abacd3)
![image](https://github.com/xnl-h4ck3r/GAP-Burp-Extension/assets/62337511/85d5c32e-fa92-4d8c-bdd8-6387944d02c3)

hello ,i have some problems.i have follow these installation instructoons exactly.https://github.com/xnl-h4ck3r/GAP-Burp-Extension/blob/main/GAP%20Help.md#how-to-install

**Comment by matthew2090218687** [comment]
Thank you, it can now be used normally. I want to match and display these. How should I configure you
username: "dask",
 password: "dask@123"
![image](https://github.com/xnl-h4ck3r/GAP-Burp-Extension/assets/62337511/069d5131-c989-4b0d-b949-884298dd4777)

**Comment by xnl-h4ck3r** [comment]
> Thank you, it can now be used normally. I want to match and display these. How should I configure you username: "dask", password: "dask@123" ![image](https://private-user-images.githubusercontent.com/62337511/325446303-069d5131-c989-4b0d-b949-884298dd4777.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0MTIzMDcsIm5iZiI6MTcxNDQxMjAwNywicGF0aCI6Ii82MjMzNzUxMS8zMjU0NDYzMDMtMDY5ZDUxMzEtYzk4OS00YjBkLWI5NDktODg0Mjk4ZGQ0Nzc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDE3MzMyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1NjNkNDA2OGVjYjExNWU3YTg2YThkZTlmNTdiZmJlNDRlZTQ2ZTdiZjljNTZkYjExZjEyMmQ5NThlNGI3NjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.E7V6sf5z85A-2zMCglWk4vFRxHKZORZJm3sPw9BWSxU)

Hi @matthew2090218687. Sorry for the late reply. Unfortunately I don't think the regex will get parameters in that kind of context at the moment. It is on the list to try to do, but I'm not sure how long that is likely to take. Can you do me a favour and create a new github issue for this, so I can close this one down as I think the original issue this issue was raised for has been resolved? Many thanks

**Comment by xnl-h4ck3r** [comment]
Hi @matthew2090218687. Actually, I think https://github.com/xnl-h4ck3r/GAP-Burp-Extension/issues/22 may be requesting the same thing. Can you just add the details of your issue to that one? Thanks
