### ISSUE TITLE
Extension not showing up in Burpsuite after installing

### ISSUE THREAD

**Issue by hackeyz** [xnl-h4ck3r/GAP-Burp-Extension#37]
I have attempted both methods of installing GAP. While the extension successfully installs and loads. it does now show as a tab in Burpsuite, neither does it open when I send a request to it.

![image](https://github.com/user-attachments/assets/5a2510c9-0c17-4e99-b12c-3b21920d7284)

**Comment by secxue** [comment]
I encountered the same problem
The version I am currently using is Burp Suite Professional v2024.5.5

**Comment by hackeyz** [comment]
I was able to fix that by running burp as root. either as sudo or from your root terminal. It seems running as non-root does not give java enough permissions to properly run packages.

**Comment by secxue** [comment]
Thank you for your answer, it is indeed a privilege issue.
I gave maximum permission to all the files related to BurpSuite, which also solved my problem
sudo chmod -R 777 ./BurpSuitePro/

**Comment by hackeyz** [comment]
Another awesome way to fix the issue. Great job man

**Comment by xnl-h4ck3r** [comment]
Thanks @hackeyz and @secxue for the solutions to this issue
