### ISSUE TITLE
AttributeError: 'module' object has no attribute '__version__'

### ISSUE THREAD

**Issue by bayusec** [xnl-h4ck3r/GAP-Burp-Extension#4]
Hi, I'm trying to install this extension but it shows me this error:

![burp](https://user-images.githubusercontent.com/13018794/206868116-3ed18e37-8cdc-4e95-a59b-07dc6a00b9c1.png)

Any thoughts on this?

**Comment by r1ghrfhd** [comment]
Delete 203 rows
