### ISSUE TITLE
Java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by br33z3** [xnl-h4ck3r/GAP-Burp-Extension#9]
Hello when I try to add this extension to my burp I am getting below error;

![image](https://user-images.githubusercontent.com/31792851/218078711-9edf237c-175c-4f80-95a2-c4b1c193cc9e.png)

**Comment by xnl-h4ck3r** [comment]
Hi @br33z3 . Thank you for taking the time to log the issue. It's not something I've seen before. Can you try making sure you have the latest version of Jython first (https://www.jython.org/download.html to see if that resolves the issue before I look into it some more?
Many thanks

**Comment by br33z3** [comment]
Hi @xnl-h4ck3r, I was use jython version 2.7.2.

I upgraded it to 2.7.3 which is the final version for jython and the issue is resolved. 

Thanks.

**Comment by xnl-h4ck3r** [comment]
Great! Thanks for using GAP
